language: java
install: true

jdk:
  - oraclejdk8
  
#permessi necessari per gradle build (exec-permission), impostati runtime
before_script:
 - chmod +x gradlew
 - ./gradle wrapper --gradle-version 5.0
 
script:
  - gradle build --scan -s
  - gradle test
