language: java
install: true

jdk:
  - oraclejdk8
  
#permessi necessari per gradle build (exec-permission), impostati runtime
before_script:
 - chmod +x gradlew
 
script:
  - ./gradlew build --scan -s
