language: java
install: true

jdk:
  - oraclejdk8

before_install:
 - chmod +x travis_scripts/install-gradle.sh
 - ./travis_scripts/install-gradle.sh
 - gradle -v
 
script:
  - gradle build --scan -s
  - gradle test
