language: java
install: true

jdk:
  - oraclejdk8
  
#permessi necessari per gradle build (exec-permission), impostati runtime
before_script:
 - chmod +x gradlew
 - ./gradlew wrapper --gradle-version=5.4.1 --distribution-type=bin
 
script:
  - gradle build --scan -s
  - gradle test
