language: java
install: true

jdk:
  - oraclejdk8

services:
  - docker

#git:
  # for cloning
  #depth: 2000

before_install:
 #install Gradle 5.0

 #- chmod +x travis_scripts/install-gradle.sh
 #- ./travis_scripts/install-gradle.sh
  - wget https://services.gradle.org/distributions/gradle-5.0-bin.zip -P /tmp
  - sudo unzip -d /opt/gradle /tmp/gradle-*.zip
  - export GRADLE_HOME=/opt/gradle/gradle-5.0
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -v

script:
  - gradle build --scan -s
  - gradle test

after_success:
  - ls RestaurantService/
  - docker build -t b95debora/restaurant:test RestaurantService/
  - docker images
