language: java
install: true

jdk:
  - oraclejdk8
  
#permessi necessari per gradle build (exec-permission), impostati runtime
before_script:
 - wget https://services.gradle.org/distributions/gradle-5.2.1-bin.zip
 - mkdir -d /opt/gradle gradle-5.2.1-bin.zip
 - ls /opt/gradle/gradle-5.4.1
 
script:
  - gradle build --scan -s
  - gradle test
