language: java
install: true

jdk:
  - oraclejdk8
#git:
  # for cloning
  #depth: 2000

jobs:
  include:
    - stage: "build"
      before_install:
        - wget https://services.gradle.org/distributions/gradle-5.0-bin.zip -P /tmp
        - sudo unzip -d /opt/gradle /tmp/gradle-*.zip
        - export GRADLE_HOME=/opt/gradle/gradle-5.0
        - export PATH=$GRADLE_HOME/bin:$PATH
        - gradle -v
      script:
        - gradle build --scan -s
    - stage: "tests"
      name: "unit tests"
      before_install:
        - wget https://services.gradle.org/distributions/gradle-5.0-bin.zip -P /tmp
        - sudo unzip -d /opt/gradle /tmp/gradle-*.zip
        - export GRADLE_HOME=/opt/gradle/gradle-5.0
        - export PATH=$GRADLE_HOME/bin:$PATH
        - gradle -v
      script: gradle test
    - name: "build image"
      services:
        - docker
      script:
        - docker build -t b95debora/restaurant:test RestaurantService/
        - docker images


