language: java
install: true

jdk:
  - oraclejdk8
  
#permessi necessari per gradle build (exec-permission), impostati runtime
before_script:
 - sudo apt-get update
 - sudo apt upgrade gradle
 - gradle -v
 
script:
  - gradle build --scan -s
  - gradle test
