version: '3'
services:
  postgres-service:
    image: postgres:latest
    volumes:
      - ./Postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres